# Generated by Django 3.1.5 on 2021-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=3000)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
