# Generated by Django 3.1.5 on 2021-03-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogportal',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogportal',
            old_name='tag',
            new_name='tags',
        ),
    ]
